### ISSUE TITLE
Crashing with two unconfirmed transactions

### ISSUE THREAD

**Issue by pik0r** [chris-belcher/electrum-personal-server#30] opened 2018-06-09 06:38 UTC
Seems it tries to access a nonexistent key. I have currently two unconfirmed transactions. 

```
 File "server.py", line 534, in <module>
    main()
  File "server.py", line 512, in main
    if not txmonitor.build_address_history(relevant_spks_addrs):
  File "/home/bitcoin/electrum-personal-server/electrumpersonalserver/transactionmonitor.py", line 145, in build_address_history
    new_history_element = self.generate_new_history_element(tx, txd)
  File "/home/bitcoin/electrum-personal-server/electrumpersonalserver/transactionmonitor.py", line 214, in generate_new_history_element
    utxo = {"confirmations": rawtx["confirmations"],
KeyError: 'confirmations'
```

**Comment by chris-belcher** [comment] 2018-06-09 22:36
That's this line https://github.com/chris-belcher/electrum-personal-server/blob/247e63061ef4686fa54660883e35931276874cc1/electrumpersonalserver/transactionmonitor.py#L214

Most likely the way to fix this is to replace `"confirmations": rawtx["confirmations"]` with `"confirmations": 0`, since we know this transaction will be unconfirmed.

**Comment by chris-belcher** [comment] 2018-06-15 14:31
The commit https://github.com/chris-belcher/electrum-personal-server/commit/538d5b613cd8ef6d8f8acb9fe5c0c0c5eaee6da1 should hopefully fix this crash. Closing this issue, it can be opened again if the same thing comes up.

**Closed by chris-belcher** 2018-06-15 14:31 UTC
