### ISSUE TITLE
Confirmed transaction still showed as "unconfirmed parent"?

### ISSUE THREAD

**Issue by andronoob** [chris-belcher/electrum-personal-server#84] opened 2019-02-04 04:04 UTC
Bitcoin Core has showed that the transaction already has 1 confirmation, but Electrum still didn't respond to this. EPS's log didn't mention that txid, either.
Not sure whether this could be reproduced, but I've came across this issue several times.

**Comment by chris-belcher** [comment] 2019-02-04 13:20
Thanks for the issue, I'll try to reproduce it on testnet when I get some time.

Since you've written "unconfirmed parent", does that mean it only happens for transactions with unconfirmed inputs?

Does it correctly show the transactions if you shut down and restart EPS ?

**Comment by andronoob** [comment] 2019-02-04 14:25
> Since you've written "unconfirmed parent", does that mean it only happens for transactions with unconfirmed inputs?

I'm not sure, but it really happened when a series of unconfirmed transactions came to the wallet. It seems that I can reproduce this, but I've not tried so many times.

> Does it correctly show the transactions if you shut down and restart EPS ?

Yes, the status turned normal after restarting EPS.

**Comment by chris-belcher** [comment] 2019-04-13 01:37
Fixed in https://github.com/chris-belcher/electrum-personal-server/commit/5a542c3fcba6d3613399e2af601aefbf6e132de0

**Closed by chris-belcher** 2019-04-13 01:37 UTC
