### ISSUE TITLE
EPS errors out with Bitcoin core v0.19.0.1

### ISSUE THREAD

**Issue by kalibox** [chris-belcher/electrum-personal-server#162] opened 2019-11-25 12:47 UTC
Hi,

I upgraded BTC core to the latest version and connecting my Electrum wallet to EPS errors out on EPS with python script errors. Is this a known issue? I'm currently away from my machine but can post error logs later today.

Thanks in advance.

Edit: I'm running EPS v0.1.7

**Comment by 0xbytes** [comment] 2019-11-25 13:38
I am getting an error too.

Traceback (most recent call last):
  File "/home/kid/.local/bin/electrum-personal-server", line 11, in <module>
    sys.exit(main())
  File "/home/kid/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line 759, in main
    run_electrum_server(rpc, txmonitor, config)
  File "/home/kid/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line 494, in run_electrum_server
    broadcast_method)
  File "/home/kid/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line 276, in handle_query
    fee_rate = 1e8*details["fee"] // details["size"]
KeyError: 'size'

**Comment by kalibox** [comment] 2019-11-25 14:02
Ah yes, those error messages look familiar to me too. 

Cheers for posting the error logs.

Thanks

**Comment by dgyg** [comment] 2019-11-25 18:11
I can confirm this issue with bitcoin-core v0.19.0.1 and EPS 0.1.7.

**Comment by notfreedude** [comment] 2019-11-25 19:48
Same issue for me. I had to go back to core 18.0.1

**Comment by chris-belcher** [comment] 2019-11-26 00:39
To solve this you need to set `deprecatedrpc=size` in bitcoin.conf

**Comment by 0xbytes** [comment] 2019-11-26 13:07
I can confirm that chris-belcher solution solves the problem. Tx Chris.

**Comment by notfreedude** [comment] 2019-11-27 17:01
Damn, I pasted deprecatedrpc=size into my conf file but EPS still crashed on me with 0.19.01

0xbytes, am I missing something?

**Comment by chris-belcher** [comment] 2019-11-27 17:15
is your `bitcoin.conf` file definitely being read by Core? Try adding `connect=0` and checking that it makes Core unable to connect to any other peer.

**Comment by pretyflaco** [comment] 2019-11-27 19:37
Is it possible EPS v0.1.7 has no issues with Bitcoin core v0.19.0., despite
 `deprecatedrpc=size` missing in `bitcoin.conf`? Mine seems to be running just fine.

**Comment by dgyg** [comment] 2019-11-27 19:56
Yes, the above mentioned parameter `deprecatedrpc=size` in `bitcoin.conf` solves the problem.

**Comment by notfreedude** [comment] 2019-11-28 02:37
@chris-belcher that didn't work for me either :-/ 

Would it help if I shared my bitcoin.conf file?

**Comment by andrewtoth** [comment] 2019-11-28 04:00
@chris-belcher this issue is fixed in master. Is there any plan to make a new release?

**Comment by 0xbytes** [comment] 2019-11-29 14:04
This is my bitcoin.conf

server=1
daemon=1
dbcache=600

rpcuser=************************[put your own username]
rpcpassword=***********************[your own password]
rpcport=8332
rpcallowip=192.168.1.0/255.255.255.0
rpcthreads=10

port=8333
bind=127.0.0.1:8333

minrelaytxfee=0.000002
limitfreerelay=6
txindex=1
maxconnections=100
deprecatedrpc=size

#tor
proxy=127.0.0.1:9050
listen=1
bind=127.0.0.1
onlynet=onion

**Comment by kalibox** [comment] 2019-12-01 13:02
Can confirm deprecatedrpc=size helps solve the issue. Thanks @chris-belcher

**Comment by chris-belcher** [comment] 2019-12-05 11:09
With the new release 0.2.0 this issue is fixed.

**Closed by chris-belcher** 2019-12-05 11:09 UTC
