### ISSUE TITLE
Invalid checksum

### ISSUE THREAD

**Issue by sjoshua270** [chris-belcher/electrum-personal-server#28] opened 2018-05-31 14:09 UTC
When I run ./server.py for the first time using rpc credentials, I get an Exception: Invalid checksum from ".electrum-server/bitcoin/deterministic.py", line 73, in bip32_deserialize

I'm using my Ledger Nano's YPUB to initiate the addresses. Is this something I can fix?

**Comment by chris-belcher** [comment] 2018-06-06 12:15
You need to get the xpub key from Electrum itself from `Wallet` -> `Information`, using the xpub keys from Ledger won't work because they use a slightly different format to Electrum.

This has tripped up other people before.

**Comment by sjoshua270** [comment] 2018-06-07 17:54
I did use Electrum to get the YPUB. The format is ypub6XG................ketg

**Comment by chris-belcher** [comment] 2018-06-08 09:05
OK then something weird is happening.

Could you try to reproduce it? Create a brand new empty ledger wallet that you won't use, and try to import the bip32 pubkey. Get it so it doesnt work and then share the bip32 key here so we can debug it.

**Comment by sjoshua270** [comment] 2018-06-13 22:39
It seems like the pub key might have been wrong because I initially created it in the Ledger wallet. You were right.

**Comment by sjoshua270** [comment] 2018-06-15 02:32
I used it to create a new wallet with native SegWit and it used zpub

On Jun 14, 2018 9:25 PM, "chris-belcher" <notifications@github.com> wrote:

So did ledger wallet create a master public key starting with ypub ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chris-belcher/electrum-personal-server/issues/28#issuecomment-397486080>,
or mute the thread

**Comment by chris-belcher** [comment] 2018-06-15 14:44
Made EPS output a hopefully more helpful error message in this situation https://github.com/chris-belcher/electrum-personal-server/commit/0b5d3c7909a8111a6484a881add0f6eae42c1765

Closing this issue for now. Can reopen if something similar comes up.

**Closed by chris-belcher** 2018-06-15 14:44 UTC
