### ISSUE TITLE
Crashes on init with can't read block from disk

### ISSUE THREAD

**Issue by ln2max** [chris-belcher/electrum-personal-server#155] opened 2019-11-03 03:57 UTC
After placing a transaction, the wallet disconnecting, and the wallet disconnecting, EPS crashed with the following exception, which also happens every time I try to restart `electrum-personal-server`:
```
Traceback (most recent call last):                                                                    File "/home/user/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line
130, in handle_query
    tx["blockhash"]])
  File "/home/user/.local/lib/python3.6/site-packages/electrumpersonalserver/server/jsonrpc.py", line
 96, in call
    raise JsonRpcError(response["error"])
electrumpersonalserver.server.jsonrpc.JsonRpcError: {'code': -32603, 'message': "Can't read block f$
om disk"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/electrum-personal-server", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line
759, in main
    run_electrum_server(rpc, txmonitor, config)
  File "/home/user/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line
494, in run_electrum_server
    broadcast_method)
  File "/home/user/.local/lib/python3.6/site-packages/electrumpersonalserver/server/common.py", line
140, in handle_query
    logger.notice("merkle proof not found for " + txid + " sending"
AttributeError: 'Logger' object has no attribute 'notice'   
```

Checking the `bitcoind` log reveals the following line corresponding to the crash:
`ERROR: ReadBlockFromDisk: OpenBlockFile failed for CDiskBlockPos(nFile=-1, nPos=0)`

**Comment by chris-belcher** [comment] 2019-11-03 07:53
Thanks for the issue, it is caused by a bug. It will be fixed in the next release. Sorry about that.

**Comment by ln2max** [comment] 2019-11-05 03:33
Is it fixed in master? Unfortunately it's hard for me to send payments
until this is fixed! Would rather not expose all my wallet to some
untrusted Electrum server just because of a bug in EPS.

**Comment by chris-belcher** [comment] 2019-11-05 08:29
I've just pushed a fix to master which you can try. I haven't had time to test it unfortunately. Hopefully it should work because its quite simple.

Since you're using pruning you'd need to run electrum with the command line argument `--skipmerklecheck` (as well as the other ones of `--oneserver` and `--server`. EPS will remind you in case you don't.

**Comment by ln2max** [comment] 2019-11-05 12:53
so 
```
git clone $EPS_GIT && cd electrum-personal-server && pip3 install wheel && pip3 install user . && cp $OLD_EPS_CONFIG .
```
should do the trick?

**Comment by chris-belcher** [comment] 2019-11-05 21:51
Maybe, try it and see?

**Comment by ln2max** [comment] 2019-11-06 07:00
That fixed it, thanks!

**Comment by chris-belcher** [comment] 2019-12-06 12:52
Fix is in new release

**Closed by chris-belcher** 2019-12-06 12:52 UTC
